version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:

# Handle the main page by serving the index page.
# Note the $ to specify the end of the path, since app.yaml does prefix matching.
- url: /$
  static_files: autocomplete.html
  upload: autocomplete.html


# Handle folder urls by serving the index.html page inside.
#- url: /(.*)/$
  #static_files: \1/index.html
  #upload: .*/index.html

# Handle nearly every other file by just serving it.
#- url: /(.+)
  #static_files: \1
  #upload: (.*)